<?php if (Mage::getStoreConfig('easybanner/info/enabled')):?>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.cycle.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/easybanner/jquery.blueberry.js')?>" type="text/javascript"></script>
<?php if ($this->isVisible()): ?>
<?php $_banner = $this->getBanner(); ?>
<?php if ($_banner->getShowTitle()==1): ?>
<h3><?php echo $_banner->getTitle(); ?></h3>
<?php endif; ?>

<script>
	$bnmini(window).load(function() {
		$bnmini('.blueberry').blueberry();
	});
</script>

<script type="text/javascript">
var $j = jQuery.noConflict(); 

  $j(document).ready(function(){
    //Setup the main rotater on the home page
    $j('#divSimpleSlider').cycle({
      speed:       <?php echo $_banner->getDelay(); ?>,
      timeout:     1500,
      pager:      '#divSimpleSliderRotate',
      pagerEvent: 'mouseover',
      fastOnEvent: false
    });
     $j('#top_banner').fadeIn(1500);
  });
</script>

<div id="top_banner" class="blueberry" style="width:<?php echo $_banner->getWidth().'%'?>; position: relative;">
    <ul id="divSimpleSlider" class="slides">   
		<?php $_banner_items = $this->getBannerItems(); ?>
		<?php foreach ($_banner_items as $_banner_item): ?>
			<li>
				<a href="<?php echo $_banner_item->getLinkUrl(); ?>" style="width:100%;" > 
				<?php if ($_banner_item->getImage()): ?>
					<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$_banner_item->getImage()?>" width="<?php echo $_banner->getWidth()?>" height="<?php echo $_banner->getHeight()?>" alt="easybanner"/>
				<?php elseif ($_banner_item->getImageUrl()): ?>
					<img src="<?php echo $_banner_item->getImageUrl() ?>" width="<?php echo $_banner->getWidth()?>" height=" <?php echo $_banner->getHeight()?>" alt="easybanner" />
				<?php endif; ?>
				</a>
			</li>
		<?php endforeach ?>
    </ul>
    <div id="divSimpleSliderRotate"></div>
<?php endif; ?>
</div>
<?php endif;?>
<div class="clear_both"><span></span></div>